/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hamza.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserProfile service. Represents a row in the &quot;HAMZA_UserProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hamza.service.model.impl.UserProfileModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hamza.service.model.impl.UserProfileImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserProfile
 * @generated
 */
@ProviderType
public interface UserProfileModel
	extends BaseModel<UserProfile>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user profile model instance should use the {@link UserProfile} interface instead.
	 */

	/**
	 * Returns the primary key of this user profile.
	 *
	 * @return the primary key of this user profile
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user profile.
	 *
	 * @param primaryKey the primary key of this user profile
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this user profile.
	 *
	 * @return the uuid of this user profile
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this user profile.
	 *
	 * @param uuid the uuid of this user profile
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the profile ID of this user profile.
	 *
	 * @return the profile ID of this user profile
	 */
	public long getProfileId();

	/**
	 * Sets the profile ID of this user profile.
	 *
	 * @param profileId the profile ID of this user profile
	 */
	public void setProfileId(long profileId);

	/**
	 * Returns the group ID of this user profile.
	 *
	 * @return the group ID of this user profile
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this user profile.
	 *
	 * @param groupId the group ID of this user profile
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this user profile.
	 *
	 * @return the company ID of this user profile
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user profile.
	 *
	 * @param companyId the company ID of this user profile
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this user profile.
	 *
	 * @return the user ID of this user profile
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this user profile.
	 *
	 * @param userId the user ID of this user profile
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user profile.
	 *
	 * @return the user uuid of this user profile
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user profile.
	 *
	 * @param userUuid the user uuid of this user profile
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this user profile.
	 *
	 * @return the user name of this user profile
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this user profile.
	 *
	 * @param userName the user name of this user profile
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this user profile.
	 *
	 * @return the create date of this user profile
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user profile.
	 *
	 * @param createDate the create date of this user profile
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user profile.
	 *
	 * @return the modified date of this user profile
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user profile.
	 *
	 * @param modifiedDate the modified date of this user profile
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this user profile.
	 *
	 * @return the first name of this user profile
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this user profile.
	 *
	 * @param firstName the first name of this user profile
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the second name of this user profile.
	 *
	 * @return the second name of this user profile
	 */
	@AutoEscape
	public String getSecondName();

	/**
	 * Sets the second name of this user profile.
	 *
	 * @param secondName the second name of this user profile
	 */
	public void setSecondName(String secondName);

	/**
	 * Returns the last name of this user profile.
	 *
	 * @return the last name of this user profile
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this user profile.
	 *
	 * @param lastName the last name of this user profile
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the first name in english of this user profile.
	 *
	 * @return the first name in english of this user profile
	 */
	@AutoEscape
	public String getFirstNameInEnglish();

	/**
	 * Sets the first name in english of this user profile.
	 *
	 * @param firstNameInEnglish the first name in english of this user profile
	 */
	public void setFirstNameInEnglish(String firstNameInEnglish);

	/**
	 * Returns the second name in english of this user profile.
	 *
	 * @return the second name in english of this user profile
	 */
	@AutoEscape
	public String getSecondNameInEnglish();

	/**
	 * Sets the second name in english of this user profile.
	 *
	 * @param secondNameInEnglish the second name in english of this user profile
	 */
	public void setSecondNameInEnglish(String secondNameInEnglish);

	/**
	 * Returns the last name in english of this user profile.
	 *
	 * @return the last name in english of this user profile
	 */
	@AutoEscape
	public String getLastNameInEnglish();

	/**
	 * Sets the last name in english of this user profile.
	 *
	 * @param lastNameInEnglish the last name in english of this user profile
	 */
	public void setLastNameInEnglish(String lastNameInEnglish);

	/**
	 * Returns the birth date of this user profile.
	 *
	 * @return the birth date of this user profile
	 */
	public Date getBirthDate();

	/**
	 * Sets the birth date of this user profile.
	 *
	 * @param birthDate the birth date of this user profile
	 */
	public void setBirthDate(Date birthDate);

	/**
	 * Returns the phone extension of this user profile.
	 *
	 * @return the phone extension of this user profile
	 */
	@AutoEscape
	public String getPhoneExtension();

	/**
	 * Sets the phone extension of this user profile.
	 *
	 * @param phoneExtension the phone extension of this user profile
	 */
	public void setPhoneExtension(String phoneExtension);

	/**
	 * Returns the phone number of this user profile.
	 *
	 * @return the phone number of this user profile
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this user profile.
	 *
	 * @param phoneNumber the phone number of this user profile
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the nationality of this user profile.
	 *
	 * @return the nationality of this user profile
	 */
	@AutoEscape
	public String getNationality();

	/**
	 * Sets the nationality of this user profile.
	 *
	 * @param nationality the nationality of this user profile
	 */
	public void setNationality(String nationality);

	/**
	 * Returns the mother tongue of this user profile.
	 *
	 * @return the mother tongue of this user profile
	 */
	@AutoEscape
	public String getMotherTongue();

	/**
	 * Sets the mother tongue of this user profile.
	 *
	 * @param motherTongue the mother tongue of this user profile
	 */
	public void setMotherTongue(String motherTongue);

	/**
	 * Returns the proof name of this user profile.
	 *
	 * @return the proof name of this user profile
	 */
	@AutoEscape
	public String getProofName();

	/**
	 * Sets the proof name of this user profile.
	 *
	 * @param proofName the proof name of this user profile
	 */
	public void setProofName(String proofName);

	/**
	 * Returns the proof number of this user profile.
	 *
	 * @return the proof number of this user profile
	 */
	@AutoEscape
	public String getProofNumber();

	/**
	 * Sets the proof number of this user profile.
	 *
	 * @param proofNumber the proof number of this user profile
	 */
	public void setProofNumber(String proofNumber);

	/**
	 * Returns the university of this user profile.
	 *
	 * @return the university of this user profile
	 */
	@AutoEscape
	public String getUniversity();

	/**
	 * Sets the university of this user profile.
	 *
	 * @param university the university of this user profile
	 */
	public void setUniversity(String university);

	/**
	 * Returns the last educational qualification of this user profile.
	 *
	 * @return the last educational qualification of this user profile
	 */
	@AutoEscape
	public String getLastEducationalQualification();

	/**
	 * Sets the last educational qualification of this user profile.
	 *
	 * @param lastEducationalQualification the last educational qualification of this user profile
	 */
	public void setLastEducationalQualification(
		String lastEducationalQualification);

	/**
	 * Returns the academic specialization of this user profile.
	 *
	 * @return the academic specialization of this user profile
	 */
	@AutoEscape
	public String getAcademicSpecialization();

	/**
	 * Sets the academic specialization of this user profile.
	 *
	 * @param academicSpecialization the academic specialization of this user profile
	 */
	public void setAcademicSpecialization(String academicSpecialization);

	/**
	 * Returns the primary language education of this user profile.
	 *
	 * @return the primary language education of this user profile
	 */
	@AutoEscape
	public String getPrimaryLanguageEducation();

	/**
	 * Sets the primary language education of this user profile.
	 *
	 * @param primaryLanguageEducation the primary language education of this user profile
	 */
	public void setPrimaryLanguageEducation(String primaryLanguageEducation);

	/**
	 * Returns the time zone of this user profile.
	 *
	 * @return the time zone of this user profile
	 */
	@AutoEscape
	public String getTimeZone();

	/**
	 * Sets the time zone of this user profile.
	 *
	 * @param timeZone the time zone of this user profile
	 */
	public void setTimeZone(String timeZone);

	/**
	 * Returns the terms accepted of this user profile.
	 *
	 * @return the terms accepted of this user profile
	 */
	public boolean getTermsAccepted();

	/**
	 * Returns <code>true</code> if this user profile is terms accepted.
	 *
	 * @return <code>true</code> if this user profile is terms accepted; <code>false</code> otherwise
	 */
	public boolean isTermsAccepted();

	/**
	 * Sets whether this user profile is terms accepted.
	 *
	 * @param termsAccepted the terms accepted of this user profile
	 */
	public void setTermsAccepted(boolean termsAccepted);

	/**
	 * Returns the file entry ID of this user profile.
	 *
	 * @return the file entry ID of this user profile
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this user profile.
	 *
	 * @param fileEntryId the file entry ID of this user profile
	 */
	public void setFileEntryId(long fileEntryId);

	@Override
	public UserProfile cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}