/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hamza.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserProfileAddress service. Represents a row in the &quot;HAMZA_UserProfileAddress&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hamza.service.model.impl.UserProfileAddressModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hamza.service.model.impl.UserProfileAddressImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserProfileAddress
 * @generated
 */
@ProviderType
public interface UserProfileAddressModel extends BaseModel<UserProfileAddress> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user profile address model instance should use the {@link UserProfileAddress} interface instead.
	 */

	/**
	 * Returns the primary key of this user profile address.
	 *
	 * @return the primary key of this user profile address
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user profile address.
	 *
	 * @param primaryKey the primary key of this user profile address
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this user profile address.
	 *
	 * @return the uuid of this user profile address
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user profile address.
	 *
	 * @param uuid the uuid of this user profile address
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the address ID of this user profile address.
	 *
	 * @return the address ID of this user profile address
	 */
	public long getAddressId();

	/**
	 * Sets the address ID of this user profile address.
	 *
	 * @param addressId the address ID of this user profile address
	 */
	public void setAddressId(long addressId);

	/**
	 * Returns the profile ID of this user profile address.
	 *
	 * @return the profile ID of this user profile address
	 */
	public long getProfileId();

	/**
	 * Sets the profile ID of this user profile address.
	 *
	 * @param profileId the profile ID of this user profile address
	 */
	public void setProfileId(long profileId);

	/**
	 * Returns the user ID of this user profile address.
	 *
	 * @return the user ID of this user profile address
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user profile address.
	 *
	 * @param userId the user ID of this user profile address
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user profile address.
	 *
	 * @return the user uuid of this user profile address
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user profile address.
	 *
	 * @param userUuid the user uuid of this user profile address
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this user profile address.
	 *
	 * @return the create date of this user profile address
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user profile address.
	 *
	 * @param createDate the create date of this user profile address
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user profile address.
	 *
	 * @return the modified date of this user profile address
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user profile address.
	 *
	 * @param modifiedDate the modified date of this user profile address
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the country of this user profile address.
	 *
	 * @return the country of this user profile address
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this user profile address.
	 *
	 * @param country the country of this user profile address
	 */
	public void setCountry(String country);

	/**
	 * Returns the state of this user profile address.
	 *
	 * @return the state of this user profile address
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this user profile address.
	 *
	 * @param state the state of this user profile address
	 */
	public void setState(String state);

	/**
	 * Returns the province of this user profile address.
	 *
	 * @return the province of this user profile address
	 */
	@AutoEscape
	public String getProvince();

	/**
	 * Sets the province of this user profile address.
	 *
	 * @param province the province of this user profile address
	 */
	public void setProvince(String province);

	/**
	 * Returns the city of this user profile address.
	 *
	 * @return the city of this user profile address
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this user profile address.
	 *
	 * @param city the city of this user profile address
	 */
	public void setCity(String city);

	/**
	 * Returns the street of this user profile address.
	 *
	 * @return the street of this user profile address
	 */
	@AutoEscape
	public String getStreet();

	/**
	 * Sets the street of this user profile address.
	 *
	 * @param street the street of this user profile address
	 */
	public void setStreet(String street);

	/**
	 * Returns the postal code of this user profile address.
	 *
	 * @return the postal code of this user profile address
	 */
	@AutoEscape
	public String getPostalCode();

	/**
	 * Sets the postal code of this user profile address.
	 *
	 * @param postalCode the postal code of this user profile address
	 */
	public void setPostalCode(String postalCode);

	@Override
	public UserProfileAddress cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}