create table HAMZA_UserProfile (
	uuid_ VARCHAR(75) null,
	profileId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	firstName VARCHAR(75) null,
	secondName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	firstNameInEnglish VARCHAR(75) null,
	secondNameInEnglish VARCHAR(75) null,
	lastNameInEnglish VARCHAR(75) null,
	birthDate DATE null,
	phoneExtension VARCHAR(75) null,
	phoneNumber VARCHAR(75) null,
	nationality VARCHAR(75) null,
	motherTongue VARCHAR(75) null,
	proofName VARCHAR(75) null,
	proofNumber VARCHAR(75) null,
	university VARCHAR(75) null,
	lastEducationalQualification VARCHAR(75) null,
	academicSpecialization VARCHAR(75) null,
	primaryLanguageEducation VARCHAR(75) null,
	timeZone VARCHAR(75) null,
	termsAccepted BOOLEAN,
	fileEntryId LONG
);

create table HAMZA_UserProfileAddress (
	uuid_ VARCHAR(75) null,
	addressId LONG not null primary key,
	profileId LONG,
	userId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	country VARCHAR(75) null,
	state_ VARCHAR(75) null,
	province VARCHAR(75) null,
	city VARCHAR(75) null,
	street VARCHAR(75) null,
	postalCode VARCHAR(75) null
);