/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hamza.service.model.impl;

import com.hamza.service.model.UserProfileAddress;
import com.hamza.service.model.UserProfileAddressModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UserProfileAddress service. Represents a row in the &quot;HAMZA_UserProfileAddress&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UserProfileAddressModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserProfileAddressImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserProfileAddressImpl
 * @generated
 */
public class UserProfileAddressModelImpl
	extends BaseModelImpl<UserProfileAddress>
	implements UserProfileAddressModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user profile address model instance should use the <code>UserProfileAddress</code> interface instead.
	 */
	public static final String TABLE_NAME = "HAMZA_UserProfileAddress";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"addressId", Types.BIGINT},
		{"profileId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"country", Types.VARCHAR}, {"state_", Types.VARCHAR},
		{"province", Types.VARCHAR}, {"city", Types.VARCHAR},
		{"street", Types.VARCHAR}, {"postalCode", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("addressId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("profileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("country", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("state_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("province", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("street", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postalCode", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table HAMZA_UserProfileAddress (uuid_ VARCHAR(75) null,addressId LONG not null primary key,profileId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,country VARCHAR(75) null,state_ VARCHAR(75) null,province VARCHAR(75) null,city VARCHAR(75) null,street VARCHAR(75) null,postalCode VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table HAMZA_UserProfileAddress";

	public static final String ORDER_BY_JPQL =
		" ORDER BY userProfileAddress.addressId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY HAMZA_UserProfileAddress.addressId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROFILEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ADDRESSID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public UserProfileAddressModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _addressId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAddressId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _addressId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserProfileAddress.class;
	}

	@Override
	public String getModelClassName() {
		return UserProfileAddress.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserProfileAddress, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserProfileAddress, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserProfileAddress, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UserProfileAddress)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserProfileAddress, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserProfileAddress, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserProfileAddress)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserProfileAddress, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserProfileAddress, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<UserProfileAddress, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<UserProfileAddress, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<UserProfileAddress, Object>>();

			attributeGetterFunctions.put("uuid", UserProfileAddress::getUuid);
			attributeGetterFunctions.put(
				"addressId", UserProfileAddress::getAddressId);
			attributeGetterFunctions.put(
				"profileId", UserProfileAddress::getProfileId);
			attributeGetterFunctions.put(
				"userId", UserProfileAddress::getUserId);
			attributeGetterFunctions.put(
				"createDate", UserProfileAddress::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", UserProfileAddress::getModifiedDate);
			attributeGetterFunctions.put(
				"country", UserProfileAddress::getCountry);
			attributeGetterFunctions.put("state", UserProfileAddress::getState);
			attributeGetterFunctions.put(
				"province", UserProfileAddress::getProvince);
			attributeGetterFunctions.put("city", UserProfileAddress::getCity);
			attributeGetterFunctions.put(
				"street", UserProfileAddress::getStreet);
			attributeGetterFunctions.put(
				"postalCode", UserProfileAddress::getPostalCode);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<UserProfileAddress, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<UserProfileAddress, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<UserProfileAddress, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<UserProfileAddress, String>)
					UserProfileAddress::setUuid);
			attributeSetterBiConsumers.put(
				"addressId",
				(BiConsumer<UserProfileAddress, Long>)
					UserProfileAddress::setAddressId);
			attributeSetterBiConsumers.put(
				"profileId",
				(BiConsumer<UserProfileAddress, Long>)
					UserProfileAddress::setProfileId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<UserProfileAddress, Long>)
					UserProfileAddress::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<UserProfileAddress, Date>)
					UserProfileAddress::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<UserProfileAddress, Date>)
					UserProfileAddress::setModifiedDate);
			attributeSetterBiConsumers.put(
				"country",
				(BiConsumer<UserProfileAddress, String>)
					UserProfileAddress::setCountry);
			attributeSetterBiConsumers.put(
				"state",
				(BiConsumer<UserProfileAddress, String>)
					UserProfileAddress::setState);
			attributeSetterBiConsumers.put(
				"province",
				(BiConsumer<UserProfileAddress, String>)
					UserProfileAddress::setProvince);
			attributeSetterBiConsumers.put(
				"city",
				(BiConsumer<UserProfileAddress, String>)
					UserProfileAddress::setCity);
			attributeSetterBiConsumers.put(
				"street",
				(BiConsumer<UserProfileAddress, String>)
					UserProfileAddress::setStreet);
			attributeSetterBiConsumers.put(
				"postalCode",
				(BiConsumer<UserProfileAddress, String>)
					UserProfileAddress::setPostalCode);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getAddressId() {
		return _addressId;
	}

	@Override
	public void setAddressId(long addressId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_addressId = addressId;
	}

	@Override
	public long getProfileId() {
		return _profileId;
	}

	@Override
	public void setProfileId(long profileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_profileId = profileId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProfileId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("profileId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getCountry() {
		if (_country == null) {
			return "";
		}
		else {
			return _country;
		}
	}

	@Override
	public void setCountry(String country) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_country = country;
	}

	@Override
	public String getState() {
		if (_state == null) {
			return "";
		}
		else {
			return _state;
		}
	}

	@Override
	public void setState(String state) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_state = state;
	}

	@Override
	public String getProvince() {
		if (_province == null) {
			return "";
		}
		else {
			return _province;
		}
	}

	@Override
	public void setProvince(String province) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_province = province;
	}

	@Override
	public String getCity() {
		if (_city == null) {
			return "";
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_city = city;
	}

	@Override
	public String getStreet() {
		if (_street == null) {
			return "";
		}
		else {
			return _street;
		}
	}

	@Override
	public void setStreet(String street) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_street = street;
	}

	@Override
	public String getPostalCode() {
		if (_postalCode == null) {
			return "";
		}
		else {
			return _postalCode;
		}
	}

	@Override
	public void setPostalCode(String postalCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_postalCode = postalCode;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, UserProfileAddress.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UserProfileAddress toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UserProfileAddress>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserProfileAddressImpl userProfileAddressImpl =
			new UserProfileAddressImpl();

		userProfileAddressImpl.setUuid(getUuid());
		userProfileAddressImpl.setAddressId(getAddressId());
		userProfileAddressImpl.setProfileId(getProfileId());
		userProfileAddressImpl.setUserId(getUserId());
		userProfileAddressImpl.setCreateDate(getCreateDate());
		userProfileAddressImpl.setModifiedDate(getModifiedDate());
		userProfileAddressImpl.setCountry(getCountry());
		userProfileAddressImpl.setState(getState());
		userProfileAddressImpl.setProvince(getProvince());
		userProfileAddressImpl.setCity(getCity());
		userProfileAddressImpl.setStreet(getStreet());
		userProfileAddressImpl.setPostalCode(getPostalCode());

		userProfileAddressImpl.resetOriginalValues();

		return userProfileAddressImpl;
	}

	@Override
	public UserProfileAddress cloneWithOriginalValues() {
		UserProfileAddressImpl userProfileAddressImpl =
			new UserProfileAddressImpl();

		userProfileAddressImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		userProfileAddressImpl.setAddressId(
			this.<Long>getColumnOriginalValue("addressId"));
		userProfileAddressImpl.setProfileId(
			this.<Long>getColumnOriginalValue("profileId"));
		userProfileAddressImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		userProfileAddressImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		userProfileAddressImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		userProfileAddressImpl.setCountry(
			this.<String>getColumnOriginalValue("country"));
		userProfileAddressImpl.setState(
			this.<String>getColumnOriginalValue("state_"));
		userProfileAddressImpl.setProvince(
			this.<String>getColumnOriginalValue("province"));
		userProfileAddressImpl.setCity(
			this.<String>getColumnOriginalValue("city"));
		userProfileAddressImpl.setStreet(
			this.<String>getColumnOriginalValue("street"));
		userProfileAddressImpl.setPostalCode(
			this.<String>getColumnOriginalValue("postalCode"));

		return userProfileAddressImpl;
	}

	@Override
	public int compareTo(UserProfileAddress userProfileAddress) {
		long primaryKey = userProfileAddress.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UserProfileAddress)) {
			return false;
		}

		UserProfileAddress userProfileAddress = (UserProfileAddress)object;

		long primaryKey = userProfileAddress.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UserProfileAddress> toCacheModel() {
		UserProfileAddressCacheModel userProfileAddressCacheModel =
			new UserProfileAddressCacheModel();

		userProfileAddressCacheModel.uuid = getUuid();

		String uuid = userProfileAddressCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			userProfileAddressCacheModel.uuid = null;
		}

		userProfileAddressCacheModel.addressId = getAddressId();

		userProfileAddressCacheModel.profileId = getProfileId();

		userProfileAddressCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			userProfileAddressCacheModel.createDate = createDate.getTime();
		}
		else {
			userProfileAddressCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			userProfileAddressCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			userProfileAddressCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		userProfileAddressCacheModel.country = getCountry();

		String country = userProfileAddressCacheModel.country;

		if ((country != null) && (country.length() == 0)) {
			userProfileAddressCacheModel.country = null;
		}

		userProfileAddressCacheModel.state = getState();

		String state = userProfileAddressCacheModel.state;

		if ((state != null) && (state.length() == 0)) {
			userProfileAddressCacheModel.state = null;
		}

		userProfileAddressCacheModel.province = getProvince();

		String province = userProfileAddressCacheModel.province;

		if ((province != null) && (province.length() == 0)) {
			userProfileAddressCacheModel.province = null;
		}

		userProfileAddressCacheModel.city = getCity();

		String city = userProfileAddressCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			userProfileAddressCacheModel.city = null;
		}

		userProfileAddressCacheModel.street = getStreet();

		String street = userProfileAddressCacheModel.street;

		if ((street != null) && (street.length() == 0)) {
			userProfileAddressCacheModel.street = null;
		}

		userProfileAddressCacheModel.postalCode = getPostalCode();

		String postalCode = userProfileAddressCacheModel.postalCode;

		if ((postalCode != null) && (postalCode.length() == 0)) {
			userProfileAddressCacheModel.postalCode = null;
		}

		return userProfileAddressCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserProfileAddress, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserProfileAddress, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserProfileAddress, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(UserProfileAddress)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UserProfileAddress>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					UserProfileAddress.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _addressId;
	private long _profileId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _country;
	private String _state;
	private String _province;
	private String _city;
	private String _street;
	private String _postalCode;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<UserProfileAddress, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UserProfileAddress)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("addressId", _addressId);
		_columnOriginalValues.put("profileId", _profileId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("country", _country);
		_columnOriginalValues.put("state_", _state);
		_columnOriginalValues.put("province", _province);
		_columnOriginalValues.put("city", _city);
		_columnOriginalValues.put("street", _street);
		_columnOriginalValues.put("postalCode", _postalCode);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("state_", "state");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("addressId", 2L);

		columnBitmasks.put("profileId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("country", 64L);

		columnBitmasks.put("state_", 128L);

		columnBitmasks.put("province", 256L);

		columnBitmasks.put("city", 512L);

		columnBitmasks.put("street", 1024L);

		columnBitmasks.put("postalCode", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UserProfileAddress _escapedModel;

}