/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hamza.service.model.impl;

import com.hamza.service.model.UserProfileAddress;
import com.hamza.service.service.UserProfileAddressLocalServiceUtil;

/**
 * The extended model base implementation for the UserProfileAddress service. Represents a row in the &quot;HAMZA_UserProfileAddress&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserProfileAddressImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserProfileAddressImpl
 * @see UserProfileAddress
 * @generated
 */
public abstract class UserProfileAddressBaseImpl
	extends UserProfileAddressModelImpl implements UserProfileAddress {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user profile address model instance should use the <code>UserProfileAddress</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			UserProfileAddressLocalServiceUtil.addUserProfileAddress(this);
		}
		else {
			UserProfileAddressLocalServiceUtil.updateUserProfileAddress(this);
		}
	}

}