/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hamza.service.model.impl;

import com.hamza.service.model.UserProfile;
import com.hamza.service.model.UserProfileModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UserProfile service. Represents a row in the &quot;HAMZA_UserProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UserProfileModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserProfileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserProfileImpl
 * @generated
 */
public class UserProfileModelImpl
	extends BaseModelImpl<UserProfile> implements UserProfileModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user profile model instance should use the <code>UserProfile</code> interface instead.
	 */
	public static final String TABLE_NAME = "HAMZA_UserProfile";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"profileId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"firstName", Types.VARCHAR}, {"secondName", Types.VARCHAR},
		{"lastName", Types.VARCHAR}, {"firstNameInEnglish", Types.VARCHAR},
		{"secondNameInEnglish", Types.VARCHAR},
		{"lastNameInEnglish", Types.VARCHAR}, {"birthDate", Types.TIMESTAMP},
		{"phoneExtension", Types.VARCHAR}, {"phoneNumber", Types.VARCHAR},
		{"nationality", Types.VARCHAR}, {"motherTongue", Types.VARCHAR},
		{"proofName", Types.VARCHAR}, {"proofNumber", Types.VARCHAR},
		{"university", Types.VARCHAR},
		{"lastEducationalQualification", Types.VARCHAR},
		{"academicSpecialization", Types.VARCHAR},
		{"primaryLanguageEducation", Types.VARCHAR},
		{"timeZone", Types.VARCHAR}, {"termsAccepted", Types.BOOLEAN},
		{"fileEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("profileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("firstNameInEnglish", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondNameInEnglish", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastNameInEnglish", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("birthDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("phoneExtension", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phoneNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nationality", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("motherTongue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("proofName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("proofNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("university", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastEducationalQualification", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("academicSpecialization", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryLanguageEducation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("timeZone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("termsAccepted", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table HAMZA_UserProfile (uuid_ VARCHAR(75) null,profileId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,firstName VARCHAR(75) null,secondName VARCHAR(75) null,lastName VARCHAR(75) null,firstNameInEnglish VARCHAR(75) null,secondNameInEnglish VARCHAR(75) null,lastNameInEnglish VARCHAR(75) null,birthDate DATE null,phoneExtension VARCHAR(75) null,phoneNumber VARCHAR(75) null,nationality VARCHAR(75) null,motherTongue VARCHAR(75) null,proofName VARCHAR(75) null,proofNumber VARCHAR(75) null,university VARCHAR(75) null,lastEducationalQualification VARCHAR(75) null,academicSpecialization VARCHAR(75) null,primaryLanguageEducation VARCHAR(75) null,timeZone VARCHAR(75) null,termsAccepted BOOLEAN,fileEntryId LONG)";

	public static final String TABLE_SQL_DROP = "drop table HAMZA_UserProfile";

	public static final String ORDER_BY_JPQL =
		" ORDER BY userProfile.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY HAMZA_UserProfile.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public UserProfileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _profileId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProfileId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _profileId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserProfile.class;
	}

	@Override
	public String getModelClassName() {
		return UserProfile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserProfile, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserProfile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserProfile, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UserProfile)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserProfile, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserProfile, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserProfile)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserProfile, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserProfile, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<UserProfile, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<UserProfile, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<UserProfile, Object>>();

			attributeGetterFunctions.put("uuid", UserProfile::getUuid);
			attributeGetterFunctions.put(
				"profileId", UserProfile::getProfileId);
			attributeGetterFunctions.put("groupId", UserProfile::getGroupId);
			attributeGetterFunctions.put(
				"companyId", UserProfile::getCompanyId);
			attributeGetterFunctions.put("userId", UserProfile::getUserId);
			attributeGetterFunctions.put("userName", UserProfile::getUserName);
			attributeGetterFunctions.put(
				"createDate", UserProfile::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", UserProfile::getModifiedDate);
			attributeGetterFunctions.put(
				"firstName", UserProfile::getFirstName);
			attributeGetterFunctions.put(
				"secondName", UserProfile::getSecondName);
			attributeGetterFunctions.put("lastName", UserProfile::getLastName);
			attributeGetterFunctions.put(
				"firstNameInEnglish", UserProfile::getFirstNameInEnglish);
			attributeGetterFunctions.put(
				"secondNameInEnglish", UserProfile::getSecondNameInEnglish);
			attributeGetterFunctions.put(
				"lastNameInEnglish", UserProfile::getLastNameInEnglish);
			attributeGetterFunctions.put(
				"birthDate", UserProfile::getBirthDate);
			attributeGetterFunctions.put(
				"phoneExtension", UserProfile::getPhoneExtension);
			attributeGetterFunctions.put(
				"phoneNumber", UserProfile::getPhoneNumber);
			attributeGetterFunctions.put(
				"nationality", UserProfile::getNationality);
			attributeGetterFunctions.put(
				"motherTongue", UserProfile::getMotherTongue);
			attributeGetterFunctions.put(
				"proofName", UserProfile::getProofName);
			attributeGetterFunctions.put(
				"proofNumber", UserProfile::getProofNumber);
			attributeGetterFunctions.put(
				"university", UserProfile::getUniversity);
			attributeGetterFunctions.put(
				"lastEducationalQualification",
				UserProfile::getLastEducationalQualification);
			attributeGetterFunctions.put(
				"academicSpecialization",
				UserProfile::getAcademicSpecialization);
			attributeGetterFunctions.put(
				"primaryLanguageEducation",
				UserProfile::getPrimaryLanguageEducation);
			attributeGetterFunctions.put("timeZone", UserProfile::getTimeZone);
			attributeGetterFunctions.put(
				"termsAccepted", UserProfile::getTermsAccepted);
			attributeGetterFunctions.put(
				"fileEntryId", UserProfile::getFileEntryId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<UserProfile, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<UserProfile, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<UserProfile, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<UserProfile, String>)UserProfile::setUuid);
			attributeSetterBiConsumers.put(
				"profileId",
				(BiConsumer<UserProfile, Long>)UserProfile::setProfileId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<UserProfile, Long>)UserProfile::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<UserProfile, Long>)UserProfile::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<UserProfile, Long>)UserProfile::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<UserProfile, String>)UserProfile::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<UserProfile, Date>)UserProfile::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<UserProfile, Date>)UserProfile::setModifiedDate);
			attributeSetterBiConsumers.put(
				"firstName",
				(BiConsumer<UserProfile, String>)UserProfile::setFirstName);
			attributeSetterBiConsumers.put(
				"secondName",
				(BiConsumer<UserProfile, String>)UserProfile::setSecondName);
			attributeSetterBiConsumers.put(
				"lastName",
				(BiConsumer<UserProfile, String>)UserProfile::setLastName);
			attributeSetterBiConsumers.put(
				"firstNameInEnglish",
				(BiConsumer<UserProfile, String>)
					UserProfile::setFirstNameInEnglish);
			attributeSetterBiConsumers.put(
				"secondNameInEnglish",
				(BiConsumer<UserProfile, String>)
					UserProfile::setSecondNameInEnglish);
			attributeSetterBiConsumers.put(
				"lastNameInEnglish",
				(BiConsumer<UserProfile, String>)
					UserProfile::setLastNameInEnglish);
			attributeSetterBiConsumers.put(
				"birthDate",
				(BiConsumer<UserProfile, Date>)UserProfile::setBirthDate);
			attributeSetterBiConsumers.put(
				"phoneExtension",
				(BiConsumer<UserProfile, String>)
					UserProfile::setPhoneExtension);
			attributeSetterBiConsumers.put(
				"phoneNumber",
				(BiConsumer<UserProfile, String>)UserProfile::setPhoneNumber);
			attributeSetterBiConsumers.put(
				"nationality",
				(BiConsumer<UserProfile, String>)UserProfile::setNationality);
			attributeSetterBiConsumers.put(
				"motherTongue",
				(BiConsumer<UserProfile, String>)UserProfile::setMotherTongue);
			attributeSetterBiConsumers.put(
				"proofName",
				(BiConsumer<UserProfile, String>)UserProfile::setProofName);
			attributeSetterBiConsumers.put(
				"proofNumber",
				(BiConsumer<UserProfile, String>)UserProfile::setProofNumber);
			attributeSetterBiConsumers.put(
				"university",
				(BiConsumer<UserProfile, String>)UserProfile::setUniversity);
			attributeSetterBiConsumers.put(
				"lastEducationalQualification",
				(BiConsumer<UserProfile, String>)
					UserProfile::setLastEducationalQualification);
			attributeSetterBiConsumers.put(
				"academicSpecialization",
				(BiConsumer<UserProfile, String>)
					UserProfile::setAcademicSpecialization);
			attributeSetterBiConsumers.put(
				"primaryLanguageEducation",
				(BiConsumer<UserProfile, String>)
					UserProfile::setPrimaryLanguageEducation);
			attributeSetterBiConsumers.put(
				"timeZone",
				(BiConsumer<UserProfile, String>)UserProfile::setTimeZone);
			attributeSetterBiConsumers.put(
				"termsAccepted",
				(BiConsumer<UserProfile, Boolean>)
					UserProfile::setTermsAccepted);
			attributeSetterBiConsumers.put(
				"fileEntryId",
				(BiConsumer<UserProfile, Long>)UserProfile::setFileEntryId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getProfileId() {
		return _profileId;
	}

	@Override
	public void setProfileId(long profileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_profileId = profileId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	@Override
	public String getSecondName() {
		if (_secondName == null) {
			return "";
		}
		else {
			return _secondName;
		}
	}

	@Override
	public void setSecondName(String secondName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_secondName = secondName;
	}

	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastName = lastName;
	}

	@Override
	public String getFirstNameInEnglish() {
		if (_firstNameInEnglish == null) {
			return "";
		}
		else {
			return _firstNameInEnglish;
		}
	}

	@Override
	public void setFirstNameInEnglish(String firstNameInEnglish) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstNameInEnglish = firstNameInEnglish;
	}

	@Override
	public String getSecondNameInEnglish() {
		if (_secondNameInEnglish == null) {
			return "";
		}
		else {
			return _secondNameInEnglish;
		}
	}

	@Override
	public void setSecondNameInEnglish(String secondNameInEnglish) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_secondNameInEnglish = secondNameInEnglish;
	}

	@Override
	public String getLastNameInEnglish() {
		if (_lastNameInEnglish == null) {
			return "";
		}
		else {
			return _lastNameInEnglish;
		}
	}

	@Override
	public void setLastNameInEnglish(String lastNameInEnglish) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastNameInEnglish = lastNameInEnglish;
	}

	@Override
	public Date getBirthDate() {
		return _birthDate;
	}

	@Override
	public void setBirthDate(Date birthDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_birthDate = birthDate;
	}

	@Override
	public String getPhoneExtension() {
		if (_phoneExtension == null) {
			return "";
		}
		else {
			return _phoneExtension;
		}
	}

	@Override
	public void setPhoneExtension(String phoneExtension) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phoneExtension = phoneExtension;
	}

	@Override
	public String getPhoneNumber() {
		if (_phoneNumber == null) {
			return "";
		}
		else {
			return _phoneNumber;
		}
	}

	@Override
	public void setPhoneNumber(String phoneNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phoneNumber = phoneNumber;
	}

	@Override
	public String getNationality() {
		if (_nationality == null) {
			return "";
		}
		else {
			return _nationality;
		}
	}

	@Override
	public void setNationality(String nationality) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nationality = nationality;
	}

	@Override
	public String getMotherTongue() {
		if (_motherTongue == null) {
			return "";
		}
		else {
			return _motherTongue;
		}
	}

	@Override
	public void setMotherTongue(String motherTongue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_motherTongue = motherTongue;
	}

	@Override
	public String getProofName() {
		if (_proofName == null) {
			return "";
		}
		else {
			return _proofName;
		}
	}

	@Override
	public void setProofName(String proofName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_proofName = proofName;
	}

	@Override
	public String getProofNumber() {
		if (_proofNumber == null) {
			return "";
		}
		else {
			return _proofNumber;
		}
	}

	@Override
	public void setProofNumber(String proofNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_proofNumber = proofNumber;
	}

	@Override
	public String getUniversity() {
		if (_university == null) {
			return "";
		}
		else {
			return _university;
		}
	}

	@Override
	public void setUniversity(String university) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_university = university;
	}

	@Override
	public String getLastEducationalQualification() {
		if (_lastEducationalQualification == null) {
			return "";
		}
		else {
			return _lastEducationalQualification;
		}
	}

	@Override
	public void setLastEducationalQualification(
		String lastEducationalQualification) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastEducationalQualification = lastEducationalQualification;
	}

	@Override
	public String getAcademicSpecialization() {
		if (_academicSpecialization == null) {
			return "";
		}
		else {
			return _academicSpecialization;
		}
	}

	@Override
	public void setAcademicSpecialization(String academicSpecialization) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_academicSpecialization = academicSpecialization;
	}

	@Override
	public String getPrimaryLanguageEducation() {
		if (_primaryLanguageEducation == null) {
			return "";
		}
		else {
			return _primaryLanguageEducation;
		}
	}

	@Override
	public void setPrimaryLanguageEducation(String primaryLanguageEducation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_primaryLanguageEducation = primaryLanguageEducation;
	}

	@Override
	public String getTimeZone() {
		if (_timeZone == null) {
			return "";
		}
		else {
			return _timeZone;
		}
	}

	@Override
	public void setTimeZone(String timeZone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_timeZone = timeZone;
	}

	@Override
	public boolean getTermsAccepted() {
		return _termsAccepted;
	}

	@Override
	public boolean isTermsAccepted() {
		return _termsAccepted;
	}

	@Override
	public void setTermsAccepted(boolean termsAccepted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_termsAccepted = termsAccepted;
	}

	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(UserProfile.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), UserProfile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UserProfile toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UserProfile>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserProfileImpl userProfileImpl = new UserProfileImpl();

		userProfileImpl.setUuid(getUuid());
		userProfileImpl.setProfileId(getProfileId());
		userProfileImpl.setGroupId(getGroupId());
		userProfileImpl.setCompanyId(getCompanyId());
		userProfileImpl.setUserId(getUserId());
		userProfileImpl.setUserName(getUserName());
		userProfileImpl.setCreateDate(getCreateDate());
		userProfileImpl.setModifiedDate(getModifiedDate());
		userProfileImpl.setFirstName(getFirstName());
		userProfileImpl.setSecondName(getSecondName());
		userProfileImpl.setLastName(getLastName());
		userProfileImpl.setFirstNameInEnglish(getFirstNameInEnglish());
		userProfileImpl.setSecondNameInEnglish(getSecondNameInEnglish());
		userProfileImpl.setLastNameInEnglish(getLastNameInEnglish());
		userProfileImpl.setBirthDate(getBirthDate());
		userProfileImpl.setPhoneExtension(getPhoneExtension());
		userProfileImpl.setPhoneNumber(getPhoneNumber());
		userProfileImpl.setNationality(getNationality());
		userProfileImpl.setMotherTongue(getMotherTongue());
		userProfileImpl.setProofName(getProofName());
		userProfileImpl.setProofNumber(getProofNumber());
		userProfileImpl.setUniversity(getUniversity());
		userProfileImpl.setLastEducationalQualification(
			getLastEducationalQualification());
		userProfileImpl.setAcademicSpecialization(getAcademicSpecialization());
		userProfileImpl.setPrimaryLanguageEducation(
			getPrimaryLanguageEducation());
		userProfileImpl.setTimeZone(getTimeZone());
		userProfileImpl.setTermsAccepted(isTermsAccepted());
		userProfileImpl.setFileEntryId(getFileEntryId());

		userProfileImpl.resetOriginalValues();

		return userProfileImpl;
	}

	@Override
	public UserProfile cloneWithOriginalValues() {
		UserProfileImpl userProfileImpl = new UserProfileImpl();

		userProfileImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		userProfileImpl.setProfileId(
			this.<Long>getColumnOriginalValue("profileId"));
		userProfileImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		userProfileImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		userProfileImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		userProfileImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		userProfileImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		userProfileImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		userProfileImpl.setFirstName(
			this.<String>getColumnOriginalValue("firstName"));
		userProfileImpl.setSecondName(
			this.<String>getColumnOriginalValue("secondName"));
		userProfileImpl.setLastName(
			this.<String>getColumnOriginalValue("lastName"));
		userProfileImpl.setFirstNameInEnglish(
			this.<String>getColumnOriginalValue("firstNameInEnglish"));
		userProfileImpl.setSecondNameInEnglish(
			this.<String>getColumnOriginalValue("secondNameInEnglish"));
		userProfileImpl.setLastNameInEnglish(
			this.<String>getColumnOriginalValue("lastNameInEnglish"));
		userProfileImpl.setBirthDate(
			this.<Date>getColumnOriginalValue("birthDate"));
		userProfileImpl.setPhoneExtension(
			this.<String>getColumnOriginalValue("phoneExtension"));
		userProfileImpl.setPhoneNumber(
			this.<String>getColumnOriginalValue("phoneNumber"));
		userProfileImpl.setNationality(
			this.<String>getColumnOriginalValue("nationality"));
		userProfileImpl.setMotherTongue(
			this.<String>getColumnOriginalValue("motherTongue"));
		userProfileImpl.setProofName(
			this.<String>getColumnOriginalValue("proofName"));
		userProfileImpl.setProofNumber(
			this.<String>getColumnOriginalValue("proofNumber"));
		userProfileImpl.setUniversity(
			this.<String>getColumnOriginalValue("university"));
		userProfileImpl.setLastEducationalQualification(
			this.<String>getColumnOriginalValue(
				"lastEducationalQualification"));
		userProfileImpl.setAcademicSpecialization(
			this.<String>getColumnOriginalValue("academicSpecialization"));
		userProfileImpl.setPrimaryLanguageEducation(
			this.<String>getColumnOriginalValue("primaryLanguageEducation"));
		userProfileImpl.setTimeZone(
			this.<String>getColumnOriginalValue("timeZone"));
		userProfileImpl.setTermsAccepted(
			this.<Boolean>getColumnOriginalValue("termsAccepted"));
		userProfileImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));

		return userProfileImpl;
	}

	@Override
	public int compareTo(UserProfile userProfile) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), userProfile.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UserProfile)) {
			return false;
		}

		UserProfile userProfile = (UserProfile)object;

		long primaryKey = userProfile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UserProfile> toCacheModel() {
		UserProfileCacheModel userProfileCacheModel =
			new UserProfileCacheModel();

		userProfileCacheModel.uuid = getUuid();

		String uuid = userProfileCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			userProfileCacheModel.uuid = null;
		}

		userProfileCacheModel.profileId = getProfileId();

		userProfileCacheModel.groupId = getGroupId();

		userProfileCacheModel.companyId = getCompanyId();

		userProfileCacheModel.userId = getUserId();

		userProfileCacheModel.userName = getUserName();

		String userName = userProfileCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			userProfileCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			userProfileCacheModel.createDate = createDate.getTime();
		}
		else {
			userProfileCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			userProfileCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			userProfileCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		userProfileCacheModel.firstName = getFirstName();

		String firstName = userProfileCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			userProfileCacheModel.firstName = null;
		}

		userProfileCacheModel.secondName = getSecondName();

		String secondName = userProfileCacheModel.secondName;

		if ((secondName != null) && (secondName.length() == 0)) {
			userProfileCacheModel.secondName = null;
		}

		userProfileCacheModel.lastName = getLastName();

		String lastName = userProfileCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			userProfileCacheModel.lastName = null;
		}

		userProfileCacheModel.firstNameInEnglish = getFirstNameInEnglish();

		String firstNameInEnglish = userProfileCacheModel.firstNameInEnglish;

		if ((firstNameInEnglish != null) &&
			(firstNameInEnglish.length() == 0)) {

			userProfileCacheModel.firstNameInEnglish = null;
		}

		userProfileCacheModel.secondNameInEnglish = getSecondNameInEnglish();

		String secondNameInEnglish = userProfileCacheModel.secondNameInEnglish;

		if ((secondNameInEnglish != null) &&
			(secondNameInEnglish.length() == 0)) {

			userProfileCacheModel.secondNameInEnglish = null;
		}

		userProfileCacheModel.lastNameInEnglish = getLastNameInEnglish();

		String lastNameInEnglish = userProfileCacheModel.lastNameInEnglish;

		if ((lastNameInEnglish != null) && (lastNameInEnglish.length() == 0)) {
			userProfileCacheModel.lastNameInEnglish = null;
		}

		Date birthDate = getBirthDate();

		if (birthDate != null) {
			userProfileCacheModel.birthDate = birthDate.getTime();
		}
		else {
			userProfileCacheModel.birthDate = Long.MIN_VALUE;
		}

		userProfileCacheModel.phoneExtension = getPhoneExtension();

		String phoneExtension = userProfileCacheModel.phoneExtension;

		if ((phoneExtension != null) && (phoneExtension.length() == 0)) {
			userProfileCacheModel.phoneExtension = null;
		}

		userProfileCacheModel.phoneNumber = getPhoneNumber();

		String phoneNumber = userProfileCacheModel.phoneNumber;

		if ((phoneNumber != null) && (phoneNumber.length() == 0)) {
			userProfileCacheModel.phoneNumber = null;
		}

		userProfileCacheModel.nationality = getNationality();

		String nationality = userProfileCacheModel.nationality;

		if ((nationality != null) && (nationality.length() == 0)) {
			userProfileCacheModel.nationality = null;
		}

		userProfileCacheModel.motherTongue = getMotherTongue();

		String motherTongue = userProfileCacheModel.motherTongue;

		if ((motherTongue != null) && (motherTongue.length() == 0)) {
			userProfileCacheModel.motherTongue = null;
		}

		userProfileCacheModel.proofName = getProofName();

		String proofName = userProfileCacheModel.proofName;

		if ((proofName != null) && (proofName.length() == 0)) {
			userProfileCacheModel.proofName = null;
		}

		userProfileCacheModel.proofNumber = getProofNumber();

		String proofNumber = userProfileCacheModel.proofNumber;

		if ((proofNumber != null) && (proofNumber.length() == 0)) {
			userProfileCacheModel.proofNumber = null;
		}

		userProfileCacheModel.university = getUniversity();

		String university = userProfileCacheModel.university;

		if ((university != null) && (university.length() == 0)) {
			userProfileCacheModel.university = null;
		}

		userProfileCacheModel.lastEducationalQualification =
			getLastEducationalQualification();

		String lastEducationalQualification =
			userProfileCacheModel.lastEducationalQualification;

		if ((lastEducationalQualification != null) &&
			(lastEducationalQualification.length() == 0)) {

			userProfileCacheModel.lastEducationalQualification = null;
		}

		userProfileCacheModel.academicSpecialization =
			getAcademicSpecialization();

		String academicSpecialization =
			userProfileCacheModel.academicSpecialization;

		if ((academicSpecialization != null) &&
			(academicSpecialization.length() == 0)) {

			userProfileCacheModel.academicSpecialization = null;
		}

		userProfileCacheModel.primaryLanguageEducation =
			getPrimaryLanguageEducation();

		String primaryLanguageEducation =
			userProfileCacheModel.primaryLanguageEducation;

		if ((primaryLanguageEducation != null) &&
			(primaryLanguageEducation.length() == 0)) {

			userProfileCacheModel.primaryLanguageEducation = null;
		}

		userProfileCacheModel.timeZone = getTimeZone();

		String timeZone = userProfileCacheModel.timeZone;

		if ((timeZone != null) && (timeZone.length() == 0)) {
			userProfileCacheModel.timeZone = null;
		}

		userProfileCacheModel.termsAccepted = isTermsAccepted();

		userProfileCacheModel.fileEntryId = getFileEntryId();

		return userProfileCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserProfile, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserProfile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserProfile, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((UserProfile)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UserProfile>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					UserProfile.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _profileId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _firstName;
	private String _secondName;
	private String _lastName;
	private String _firstNameInEnglish;
	private String _secondNameInEnglish;
	private String _lastNameInEnglish;
	private Date _birthDate;
	private String _phoneExtension;
	private String _phoneNumber;
	private String _nationality;
	private String _motherTongue;
	private String _proofName;
	private String _proofNumber;
	private String _university;
	private String _lastEducationalQualification;
	private String _academicSpecialization;
	private String _primaryLanguageEducation;
	private String _timeZone;
	private boolean _termsAccepted;
	private long _fileEntryId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<UserProfile, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UserProfile)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("profileId", _profileId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("secondName", _secondName);
		_columnOriginalValues.put("lastName", _lastName);
		_columnOriginalValues.put("firstNameInEnglish", _firstNameInEnglish);
		_columnOriginalValues.put("secondNameInEnglish", _secondNameInEnglish);
		_columnOriginalValues.put("lastNameInEnglish", _lastNameInEnglish);
		_columnOriginalValues.put("birthDate", _birthDate);
		_columnOriginalValues.put("phoneExtension", _phoneExtension);
		_columnOriginalValues.put("phoneNumber", _phoneNumber);
		_columnOriginalValues.put("nationality", _nationality);
		_columnOriginalValues.put("motherTongue", _motherTongue);
		_columnOriginalValues.put("proofName", _proofName);
		_columnOriginalValues.put("proofNumber", _proofNumber);
		_columnOriginalValues.put("university", _university);
		_columnOriginalValues.put(
			"lastEducationalQualification", _lastEducationalQualification);
		_columnOriginalValues.put(
			"academicSpecialization", _academicSpecialization);
		_columnOriginalValues.put(
			"primaryLanguageEducation", _primaryLanguageEducation);
		_columnOriginalValues.put("timeZone", _timeZone);
		_columnOriginalValues.put("termsAccepted", _termsAccepted);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("profileId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("firstName", 256L);

		columnBitmasks.put("secondName", 512L);

		columnBitmasks.put("lastName", 1024L);

		columnBitmasks.put("firstNameInEnglish", 2048L);

		columnBitmasks.put("secondNameInEnglish", 4096L);

		columnBitmasks.put("lastNameInEnglish", 8192L);

		columnBitmasks.put("birthDate", 16384L);

		columnBitmasks.put("phoneExtension", 32768L);

		columnBitmasks.put("phoneNumber", 65536L);

		columnBitmasks.put("nationality", 131072L);

		columnBitmasks.put("motherTongue", 262144L);

		columnBitmasks.put("proofName", 524288L);

		columnBitmasks.put("proofNumber", 1048576L);

		columnBitmasks.put("university", 2097152L);

		columnBitmasks.put("lastEducationalQualification", 4194304L);

		columnBitmasks.put("academicSpecialization", 8388608L);

		columnBitmasks.put("primaryLanguageEducation", 16777216L);

		columnBitmasks.put("timeZone", 33554432L);

		columnBitmasks.put("termsAccepted", 67108864L);

		columnBitmasks.put("fileEntryId", 134217728L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UserProfile _escapedModel;

}